---
title: "Importing NIF data sets"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{importing-NIF-datasets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette describes how to import NIF data sets not created  with
`make_nif()`.

# BACKGROUND

NIF data sets created from SDTM data using `make_nif()` inherit fields from the
original data that provide information on the analyte. These fields include:

* `ANALYTE` (character), the name of the analyte/the administered drug. This
field is derived from the `PCTESTCD` variable of the SDTM domain 'PC'. Please
see the `vignette("nif-vignette")` and the documentation to
`add_treatment_mapping()` for details on how the analyte name can be linked to
the respective drug name (i.e., `EXTRT` in the SDTM domain 'EX'). The `ANALYTE`
name is used for both, observations and administrations of the compound.

* `PARENT` (character), the name of the parent compound that the analyte belongs
to. This is the same as the `ANALYTE` for parent compounds. However, if
metabolite observations are included in the data set, the `PARENT` field is the
name of the respective parent compound. The association between analytes and
their respective parent compound can be established by
`add_metabolite_mapping()`, see also the `vignette("nif-vignette")`.

* `METABOLITE` (logical), the information whether the analyte represents a
metabolite compound, i.e., is not administered.

The above fields are particularly important in cases where a NIF data set
contains administrations and observations of multiple drugs, e.g., data from
drug combinations studies or PK/PD data that include observations from plasma
concentrations and other endpoints.

