#' nif class constructor
#'
#' @param nif.data A data frame containing the actual NIF data as generated by,
#'   e.g, [make_nif()].
#' @import dplyr
#' @return A nif object from the input data set.
#' @export
nif <- function(nif.data) {
  temp <- nif.data
  class(temp) <- c("nif", "data.frame")
  return(temp)
}


#' print() implementation for nif objects
#'
#' @param obj A nif object.
#' @export
print.nif <- function(obj){
  cat(paste("NONMEM input file (NIF) with data from",
            length(studies(obj)),
            "studies\n"))
  n.obs <- obj %>%
    filter(EVID==0) %>%
    nrow()
  cat(paste(n.obs, "observations from",
            length(subjects(obj)), "subjects\n"))

  n.sex <- obj %>%
    dplyr::distinct(USUBJID, SEX) %>%
    dplyr::group_by(SEX) %>%
    dplyr::summarize(n=n())

  n_males <- n.sex %>%
    dplyr::filter(SEX==0) %>%
    dplyr::pull(n)
  if(length(n_males)==0) {n_males=0}

  n_females <- n.sex %>%
    dplyr::filter(SEX==1) %>%
    dplyr::pull(n)
  if(length(n_females)==0) {n_females=0}

  cat(paste0("Males: ", n_males, ", females: ", n_females, " (",
             round(n_females/(n_males + n_females)*100, 1), "%)\n\n"))

  cat(paste0("Studies:\n", paste(studies(obj), collapse="\n"), "\n\n"))
  cat(paste0("Doses:\n", paste(doses(obj), collapse=", "), "\n\n"))
  cat("Columns:\n")
  cat(paste(names(obj), collapse=", "), "\n")
  temp <- obj %>%
    dplyr::select(ID, NTIME, TIME, ANALYTE, EVID, AMT, DOSE, DV) %>%
    df.to.string(n=15)
  cat(paste0("\nFirst rows of NIF data (selected columns):\n", temp))
}


#' Subjects within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A character vector of all USUBJIDs in the data set.
#' @export
subjects.nif <- function(obj) {
  obj %>%
    dplyr::distinct(USUBJID) %>%
    dplyr::pull(USUBJID)
}


#' Studies within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A character vector of all STUDYIDs in the data set.
#' @export
subjects <- function(obj) {
  UseMethod("subjects")
}


#' Studies within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A character vector of all STUDYIDs in the data set.
#' @export
studies.nif <- function(obj) {
  obj %>%
    dplyr::distinct(STUDYID) %>%
    dplyr::pull(STUDYID)
}

#' @export
studies <- function(obj) {
  UseMethod("studies")
}

#' Doses within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A number vector of all doses (AMT) in the data set.
#' @export
doses <- function(obj) {
  UseMethod("doses")
}

#' Doses within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A number vector of all doses (AMT) in the data set.
#' @export
doses.nif <- function(obj){
  obj %>%
    dplyr::filter(AMT!=0) %>%
    dplyr::distinct(AMT) %>%
    dplyr::arrange(as.numeric(AMT)) %>%
    dplyr::pull(AMT)
}

#' Analytes within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A character vector of all analytes in the data set.
#' @export
analytes <- function(obj) {
  UseMethod("analytes")
}

#' Analytes within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A character vector of all analytes in the data set.
#' @export
analytes.nif <- function(obj){
  obj %>%
    # dplyr::filter(AMT!=0) %>%
    dplyr::distinct(ANALYTE) %>%
    # dplyr::arrange(as.numeric(AMT)) %>%
    dplyr::pull(ANALYTE)
}

#' Export a nif object as csv file
#'
#' @param obj A nif object.
#' @param filename The filename for the exported file.
#' @import dplyr
#' @export
write_csv <- function(obj, filename) {
  UseMethod("write_csv")
}

#' Export a nif object as csv file
#'
#' @param obj A nif object.
#' @param filename The filename for the exported file.
#' @import dplyr
#' @export
write_csv.nif <- function(obj, filename){
  temp <- obj %>%
    dplyr::mutate(across(c("TIME", "LNDV"), round, 3))
  write.csv(temp, filename, quote=F, row.names=F)
}


#' Standard nif fields
#'
#' @return A character vector of the standard NIF fields
#' @export
standard_nif_fields <- c("REF", "STUDYID", "ID", "USUBJID", "NTIME", "TIME",
                         "ANALYTE", "AMT", "RATE", "DV", "LNDV", "CMT", "EVID",
                         "DOSE", "AGE", "SEX", "RACE", "HEIGHT", "WEIGHT",
                         "ACTARMCD")

#' Plot NIF data set by dose and analyte
#'
#' @param obj The NIF object to be plotted.
#' @param y_scale Type of y-axis scale. Can be 'log' or 'lin'. Default is "lin".
#' @param max_x Maximal x (time) scale value.
#' @param analyte The analyte to be plotted If this argument is not supplied
#'   (or set to NULL), all analytes are shown.
#' @param mean Boolean value to indicate whether the mean value by dose and
#'   analyte is to be plotted. In that case, the nominal time (NTIME) is shown
#'   on the x axis. 'mean=T' will cast an error if multiple analytes are in the
#'   data set of have been defined with 'analyte'.
#' @param doses The doses to be plotted. Can be a scalar value or a numeric
#'   vector or NULL to plot all doses.
#' @param points Boolean value to define whether points should be plotted.
#' @param id Numerical scalar or vector of IDs to be plotted.
#' @param usubjid Character scalar or vector of USUBJIDs to be plotted.
#' @param group Character scalar to define a grouping variable. If specified,
#'   this will cast an error if multiple analytes are in the data set or have
#'   been defined by 'analyte'.
#' @return The plot object
#' @seealso [nif_viewer()]
#' @export
plot <- function(obj, y_scale="lin", max_x=NULL, analyte=NULL, mean=FALSE,
                 doses=NULL, points=F, id=NULL, usubjid=NULL, group=NULL){
  UseMethod("plot")
}

#' Plot nif data set
#'
#' @export
plot.nif <- function(obj, y_scale="lin", max_x=NULL, analyte=NULL, mean=FALSE,
                     doses=NULL, points=F, id=NULL, usubjid=NULL,
                     group=NULL) {
  if(!is.null(id)) {
    obj <- obj %>%
      dplyr::filter(ID %in% id)
  }

  if(!is.null(usubjid)) {
    obj <- obj %>%
      dplyr::filter(USUBJID %in% usubjid)
  }

  if(!is.null(analyte)) {
    obj <- obj %>%
      dplyr::filter(ANALYTE==analyte)
  }

  if(!is.null(doses)){
    obj <- obj %>%
      dplyr::filter(DOSE %in% doses)
  }

  if(!is.null(group)){
    cov <- group
    if(is.null(analyte) | length(analyte) > 1){
      stop(paste0("Plotting multiple analytes in the same graph does not make ",
                  "sense. Consider selecting a (single) analyte!"))
    }
  } else {
    cov <- "ANALYTE"
  }

  if(mean==TRUE){
    if(!is.null(group) & is.null(analyte) & length(analytes(obj)>1)){
      stop(paste0("Plotting means over multiple analytes does not make sense! ",
                   "Consider selecting a specific analyte"))
    }
    p <- obj %>%
      dplyr::filter(!is.na(DOSE)) %>%
      dplyr::group_by(NTIME, .data[[cov]], DOSE) %>%
      dplyr::summarize(mean=mean(DV, na.rm=TRUE), sd=sd(DV, na.rm=TRUE), n=n()) %>%
      ggplot2::ggplot(ggplot2::aes(
        x=NTIME, y=mean,
        group=as.factor(.data[[cov]]),
        color=as.factor(.data[[cov]]))) +
      ggplot2::geom_ribbon(aes(ymin=mean-sd, ymax=mean+sd,
                               fill=as.factor(.data[[cov]])),
                               alpha=0.3, color=NA, show.legend=F) +
      ggplot2::geom_line() +
      ggplot2::facet_wrap(~DOSE) +
      ggplot2::theme_bw() +
      ggplot2::theme(legend.position="bottom") +
      ggplot2::labs(title="DV over time by dose", fill=NULL)
  } else {
    p <- obj %>%
      dplyr::filter(!is.na(DOSE)) %>%
      ggplot2::ggplot(ggplot2::aes(
        x=TIME, y=DV,
        group=interaction(USUBJID, ANALYTE, as.factor(.data[[cov]])),
        color=as.factor(.data[[cov]]))) +
      ggplot2::geom_line() +
      ggplot2::facet_wrap(~DOSE) +
      ggplot2::theme_bw() +
      ggplot2::theme(legend.position="bottom") +
      ggplot2::labs(title="DV over time by dose")
  }

  if(!is.null(max_x)) {
    p <- p + ggplot2::xlim(0, max_x)
  }

  if(y_scale=="log"){
    p <- p + ggplot2::scale_y_log10()
  }

  if(points){
    p <- p + ggplot2::geom_point()
  }

  # if(!is.null(analyte) & length(analyte) == 1){
  if(length(analyte) == 1){
    p <- p + labs(y=analyte)
  }

  if(!is.null(group)) {
    p <- p + labs(color=group)
  } else {
    p <- p + labs(color="ANALYTE")
  }

  return(p)
}

