#' nif class constructor
#'
#' @param nif.data A data frame containing the actual NIF data as generated by,
#'   e.g, [make_nif()].
#' @import dplyr
#' @return A nif object from the input data set.
#' @export
nif <- function(nif.data) {
  temp <- nif.data
  class(temp) <- c("nif", "data.frame")
  return(temp)
}


#' print() implementation for nif objects
#'
#' @param obj A nif object.
#' @export
print.nif <- function(obj){
  cat(paste("NONMEM input file (NIF) with data from",
            length(studies(obj)),
            "studies\n"))
  n.obs <- obj %>%
    filter(EVID==0) %>%
    nrow()
  cat(paste(n.obs, "observations from",
            length(subjects(obj)), "subjects\n"))
  n.sex <- obj %>%
    dplyr::distinct(USUBJID, SEX) %>%
    dplyr::group_by(SEX) %>%
    dplyr::summarize(n=n())

  cat(paste0("Females: ", n.sex %>%
               dplyr::filter(SEX==1) %>%
               dplyr::pull(n), ", ",
            "Males: ", n.sex %>%
              dplyr::filter(SEX==0) %>%
              dplyr::pull(n)), "\n\n")

  cat(paste0("Studies:\n", paste(studies(obj), collapse="\n"), "\n\n"))
  cat(paste0("Doses:\n", paste(doses(obj), collapse=", "), "\n\n"))
  cat("Fields:\n")
  cat(paste(names(obj), collapse=", "), "\n")
}


#' Subjects within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A character vector of all USUBJIDs in the data set.
#' @export
subjects.nif <- function(obj) {
  obj %>%
    dplyr::distinct(USUBJID) %>%
    dplyr::pull(USUBJID)
}


#' Studies within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A character vector of all STUDYIDs in the data set.
#' @export
subjects <- function(obj) {
  UseMethod("subjects")
}


#' Studies within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A character vector of all STUDYIDs in the data set.
#' @export
studies.nif <- function(obj) {
  obj %>%
    dplyr::distinct(STUDYID) %>%
    dplyr::pull(STUDYID)
}

#' @export
studies <- function(obj) {
  UseMethod("studies")
}

#' Doses within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A number vector of all doses (AMT) in the data set.
#' @export
doses <- function(obj) {
  UseMethod("doses")
}


#' Doses within a nif object
#'
#' @param obj A nif object
#' @import dplyr
#' @return A number vector of all doses (AMT) in the data set.
#' @export
doses.nif <- function(obj){
  obj %>%
    dplyr::filter(AMT!=0) %>%
    dplyr::distinct(AMT) %>%
    dplyr::arrange(as.numeric(AMT)) %>%
    dplyr::pull(AMT)
}

#' Export a nif object as csv file
#'
#' @param obj A nif object.
#' @param filename The filename for the exported file.
#' @import dplyr
#' @export
write_csv <- function(obj, filename) {
  UseMethod("write_csv")
}

#' Export a nif object as csv file
#'
#' @param obj A nif object.
#' @param filename The filename for the exported file.
#' @import dplyr
#' @export
write_csv.nif <- function(obj, filename){
  temp <- obj %>%
    dplyr::mutate(across(c("TIME", "LNDV"), round, 3))
  write.csv(temp, filename, quote=F, row.names=F)
}


#' Standard nif fields
#'
#' @return A character vector of the standard NIF fields
#' @export
standard_nif_fields <- c("REF", "STUDYID", "ID", "USUBJID", "NTIME", "TIME",
                         "ANALYTE", "AMT", "RATE", "DV", "LNDV", "CMT", "EVID",
                         "DOSE", "AGE", "SEX", "RACE", "HEIGHT", "WEIGHT",
                         "ACTARMCD")

#' Plot nif data set
#'
#' @param obj The nif object
#' @param y_scale Type of y-axis scale. Can be 'log' or 'lin' (default).
#' @return The plot object
#' @export
plot <- function(obj, y_scale="lin"){
  UseMethod("plot")
}

#' Plot nif data set
#'
#' @param obj The nif object
#' @param y_scale Type of y-axis scale. Can be 'log' or 'lin' (default).
#' @return The plot object
#' @export
plot.nif <- function(obj, y_scale="lin") {
  p <- obj %>%
    filter(!is.na(DOSE)) %>%
    ggplot2::ggplot(ggplot2::aes(x=TIME, y=DV,
      group=interaction(USUBJID, ANALYTE),
      color=ANALYTE)) +
    ggplot2::geom_line() +
    #ggplot2::xlim(0, 25) +
    ggplot2::facet_wrap(~DOSE) +
    ggplot2::theme_bw() +
    ggplot2::theme(legend.position="bottom") +
    ggplot2::labs(title="DV over time by dose")

  if(y_scale=="log"){
    p <- p + scale_y_log10()
  }
  return(p)
}
